server:
  port: 8085
spring:
  application:
    name: history-manager
  kafka:
    bootstrap-servers: localhost:29092, localhost:39092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:29092, localhost:39092
    consumer:
      bootstrap-servers: localhost:29092, localhost:39092
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5433/historydb
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

kafkaprops:
  groupId: ${spring.application.name}
  eventsTopicName: "events.public.crud_events"
  bootstrapServers: localhost:29092, localhost:39092
  backoff:
    initial-interval: 500ms
    max-interval: 2s
    max-retries: 4
    multiplier: 1.5
  deadletter:
    retention: 28d
    suffix: .DLT